---
title: "lab10_warmup"
author: "Jocelyn Morales"
date: "2024-02-15"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. In the data folder there is an epidemiology data set on an outbreak of malaria. 
```{r}
library(tidyverse)
library(janitor)
```

```{r}
malaria <- read_csv("data/malaria.csv") %>%  clean_names()
```
## 2. rdt refers to rapid diasgnostic test and they are identified here by age group. 
```{r}
names(malaria)
```

## 3. Make the data tidy and store them as a new object 
```{r}
malaria_2 <- malaria %>% 
  pivot_longer(cols = starts_with("malaria_rdt"),
               names_to = "age_class",
               values_to = "cases") %>% 
  select(newid, data_date, submitted_date, location_name, province, district, age_class, cases)
```

## 4. Which district had the highest total number of cases on July 30, 2020
```{r}
malaria_2 %>% 
  filter(data_date=="2020-07-30") %>% 
  group_by(district) %>% 
  summarise(tot_cases= sum(cases, na.rm =T)) %>% 
  arrange(-tot_cases)
```

