---
title: "lab6_warmup"
author: "Jocelyn Morales"
date: "2024-01-30"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Load the bison.csv data 

```{r}
library("tidyverse")
```

```{r}
getwd()
```

```{r}
bison <- read.csv("data/bison.csv")
```

### 2. What are the dimensions and structure of the data 

```{r}
dim(bison)
```

```{r}
str(bison)
```

### 3. We are only interested in code, sex, weight, year of birth. Restrict the data to these variables and store the datafame as a new object. 
```{r}
bison_new <- select(bison, "animal_code", "animal_sex", "animal_weight", "animal_yob")
```

```{r}
bison %>%
  select(animal_code, animal_sex, animal_weight, animal_yob)
```

### 4. Pull out the animals born between 1980-1990. 

```{r}
filter(bison_new, between(animal_yob, 1980, 1990))
```

### 5. How many male and female bison are represented between 1980-1990?

```{r}
filter(bison_new, animal_sex=="M")
```

```{r}
filter(bison_new, animal_sex=="F")
```

### 6. Between 1980-1990, were males or females larger on average? 

```{r}
males <- filter(bison_new, animal_sex=="M")
```

```{r}
mean(males$animal_weight, na.rm = T)
```

```{r}
females <- filter(bison_new, animal_sex=="F")
```

```{r}
mean(females$animal_weight)
```

